import Head from 'next/head'
import Link from 'next/link'
import { useRef } from 'react'
import Footer from '../components/footer/Footer'
import Header from '../components/Header/Header'
import Page from '../components/Page'

export default function Home() {


  return (
    <div  className='flex  flex-col h-screen items-center justify-center'>
      <Head>
        <title> GOOGLE </title>{' '}
        <meta
          name='cloning google with nextjs'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>{' '}
      <Header />
      <Page />
      <Footer/>
    </div>
  )
}
